### ISSUE TITLE
Connect to non-standard port via ssh

### ISSUE THREAD

**Issue by blinse** [cloudfoundry-samples/cf-ex-wordpress#9]
Great project. My ssh-server is running on a non-standard port other than 22. Is there any way I can use this project with my server to store the wordpress/php files?

**Comment by dmikusa-pivotal** [comment]
I think you can do this with SSH_OPTS.

https://github.com/cloudfoundry-samples/cf-ex-wordpress/blob/master/manifest.yml#L14

Add an option `-o port=2222` or whatever your port number is.

**Comment by blinse** [comment]
Thanks. This works.
